set.seed(46)
x <- runif(1000)
r <- mf_distr(x)
expect_equal(r$bw, target = 0.04413086, tolerance = 1e-7)
expect_equal(r$nbins, target = 11)
expect_silent(mf_distr(x, nbins = 11))
expect_silent(mf_distr(x, nbins = 11, bw = .1))
expect_silent(mf_distr(x))
expect_silent(mf_distr(x, bw = .1))
